### ISSUE TITLE
InfluxDB addon restart infinite loop

### ISSUE THREAD

**Issue by welcoMattic** [hassio-addons/addon-influxdb#118]
# Problem/Motivation

InfluxDB addon in restarting in infinite loop

## Expected behavior

InfluxDB start once for all

## Actual behavior

InfluxDB addon in restarting in infinite loop

## Steps to reproduce

Home Assistant OS 5.10
core-2021.1.5
supervisor-2021.01.7
InfluxDB Addon 4.0.1 

Logs supervisor:

```
21-02-01 16:06:11 WARNING (MainThread) [supervisor.misc.tasks] Watchdog found a problem with a0d7b954_influxdb!
21-02-01 16:06:12 INFO (SyncWorker_0) [supervisor.docker.interface] Cleaning addon_a0d7b954_influxdb application
21-02-01 16:06:13 INFO (SyncWorker_0) [supervisor.docker.addon] Starting Docker add-on ghcr.io/hassio-addons/influxdb/armv7 with version 4.0.1
21-02-01 16:06:15 INFO (MainThread) [supervisor.api.security] /dns/info access from a0d7b954_influxdb
``` 

Repeated many times

Logs core:

```
2021-02-01 17:07:23 ERROR (SyncWorker_2) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa7acb970>: Failed to establish a new connection: [Errno 111] Connection refused'))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
```

Repeated many times

**Comment by sinclairpaul** [comment]
Can you post the addon log and config?

**Comment by welcoMattic** [comment]
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: InfluxDB
 Scalable datastore for metrics, events, and real-time analytics
-----------------------------------------------------------
 Add-on version: 4.0.1
 You are running the latest version of this add-on.
 System: Home Assistant OS 5.10  (armv7 / raspberrypi4)
 Home Assistant Core: 2021.1.5
 Home Assistant Supervisor: 2021.01.7
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] create-users.sh: executing... 
[cont-init.d] create-users.sh: exited 0.
[cont-init.d] influxdb.sh: executing... 
[cont-init.d] influxdb.sh: exited 0.
[cont-init.d] kapacitor.sh: executing... 
[cont-init.d] kapacitor.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[11:18:22] INFO: Kapacitor is waiting until InfluxDB is available...
[11:18:22] INFO: Chronograf is waiting until InfluxDB is available...
[11:18:22] INFO: Starting the InfluxDB...

goroutine 998 [chan receive]:
github.com/influxdata/influxdb/services/subscriber.chanWriter.Run(0x1e323e80, 0x1e9c570, 0x1d0ede90, 0x3f46c28, 0x3f46c30, 0x3f3f140)
	/go/src/github.com/influxdata/influxdb/services/subscriber/service.go:372 +0x38
github.com/influxdata/influxdb/services/subscriber.(*Service).updateSubs.func1(0x10d58d50, 0x1e323e80, 0x1e9c570, 0x1d0ede90, 0x3f46c28, 0x3f46c30, 0x3f3f140)
	/go/src/github.com/influxdata/influxdb/services/subscriber/service.go:314 +0x4c
created by github.com/influxdata/influxdb/services/subscriber.(*Service).updateSubs
	/go/src/github.com/influxdata/influxdb/services/subscriber/service.go:312 +0x79c

... (x100 the same log 'goroutine XXXX [chan receive]')
```

**Comment by welcoMattic** [comment]
The configuration:

```yaml
auth: true
reporting: true
ssl: true
certfile: fullchain.pem
keyfile: privkey.pem
envvars: []
```

**Comment by welcoMattic** [comment]
It's still broken after HassOS and supervisor updates

**Comment by rikman122** [comment]
I'm facing the same issue, same addon log and configuration

**Comment by frenck** [comment]
Please try upgrading to version 4.0.3, which has just been released.

**Comment by rikman122** [comment]
I updated it before posting here so I can confirm the issue continues in the last version

**Comment by welcoMattic** [comment]
I finally uninstall/reinstall completely the add-on, and it works now.

**Comment by rikman122** [comment]
Did you lost the data stored when reinstalling the addon?

**Comment by welcoMattic** [comment]
Yes I lost all my data.

**Comment by frenck** [comment]
Man, that just sucks @welcoMattic. I have not been able to reproduce it and do not have any idea on where to start on this one either :(

**Comment by welcoMattic** [comment]
It doesn't matter, I had not a very big data history in InfluxDB, only some temperature and network bandwidth records. I was able to reimport all my electricity consumption data from a distant API. That's why I've done a uninstall/reinstall of the addon. Otherwise, I would have tried to fix the problem :D

**Comment by rikman122** [comment]
Aww that's a pain for me, I have a lot of data stored. I'll try to troubleshoot this and let you guys know.
