### ISSUE TITLE
InfluxDB installs, but can't be enabled in configuration.yaml

### ISSUE THREAD

**Issue by franzbischoff** [hassio-addons/addon-influxdb#201]
# Problem/Motivation

InfluxDB can be installed and the docker runs, but I cant integrate with HA

## Expected behavior

After enabling the "influxdb:" line in configuration.yaml, server should accept the config as correct, but it stalls

## Steps to reproduce

I just installed the Influxdb addon. I tried to uninstall, install again, reboot the whole server, etc.
Just install, and try to enable the integration with HA, after that, check logs.

## Proposed changes

It may be some library incompatibility (just a thought).

Here is one of the error messages:

```
Logger: homeassistant.setup
Source: components/influxdb/__init__.py:13
First occurred: 21:28:37 (1 occurrences)
Last logged: 21:28:37

Setup failed for influxdb: unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 201, in _async_setup_component
    component = integration.get_component()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 490, in get_component
    cache[self.domain] = importlib.import_module(self.pkg_path)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/src/homeassistant/homeassistant/components/influxdb/__init__.py", line 13, in <module>
    from influxdb import InfluxDBClient, exceptions
  File "/usr/local/lib/python3.9/site-packages/influxdb/__init__.py", line 10, in <module>
    from .dataframe_client import DataFrameClient
  File "/usr/local/lib/python3.9/site-packages/influxdb/dataframe_client.py", line 12, in <module>
    import pandas
  File "/usr/local/lib/python3.9/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import (
  File "/usr/local/lib/python3.9/site-packages/pandas/compat/__init__.py", line 15, in <module>
    from pandas.compat.numpy import (
  File "/usr/local/lib/python3.9/site-packages/pandas/compat/numpy/__init__.py", line 7, in <module>
    from pandas.util.version import Version
  File "/usr/local/lib/python3.9/site-packages/pandas/util/__init__.py", line 1, in <module>
    from pandas.util._decorators import (  # noqa
  File "/usr/local/lib/python3.9/site-packages/pandas/util/_decorators.py", line 14, in <module>
    from pandas._libs.properties import cache_readonly  # noqa
  File "/usr/local/lib/python3.9/site-packages/pandas/_libs/__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
```

**Comment by frenck** [comment]
You are report an issue with an Home Assistant integration with the add-on.
Please report issues with integrations of Home Assistant with the Home Assistant project. That is not related to this add-on project.
