### ISSUE TITLE
Error backing up addon and update addon

### ISSUE THREAD

**Issue by antoweb** [hassio-addons/addon-influxdb#217]
# Problem/Motivation
When try update addon return an error

21-10-28 21:53:37 ERROR (MainThread) [supervisor.jobs] Unhandled exception: 'a0d7b954_influxdb'
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 106, in wrapper
    return await self._method(*args, **kwargs)
  File "/usr/src/supervisor/supervisor/addons/__init__.py", line 265, in update
    store = self.store[slug]
KeyError: 'a0d7b954_influxdb'
21-10-28 21:54:08 ERROR (MainThread) [supervisor.jobs] Unhandled exception: 'a0d7b954_influxdb'
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 106, in wrapper
    return await self._method(*args, **kwargs)
  File "/usr/src/supervisor/supervisor/addons/__init__.py", line 265, in update
    store = self.store[slug]
KeyError: 'a0d7b954_influxdb'
> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by nickdos** [comment]
Also seeing this - using the upgrade option on the "supervisor" UI fails every time, so I'm not able to upgrade at this point.
