### ISSUE TITLE
Unable to import component: Exception importing homeassistant.components.influxdb

### ISSUE THREAD

**Issue by Palmdale95** [hassio-addons/addon-influxdb#332]
Hi there,
I am using the influxes add on in homeassistant and after upgrading the HA core from 2024.3.3 to 2024.4.1 I am getting this error message:
#Logger: homeassistant.setup
Quelle: setup.py:316
Erstmals aufgetreten: 13:40:27 (1 Vorkommnisse)
Zuletzt protokolliert: 13:40:27

Setup failed for 'influxdb': Unable to import component: Exception importing homeassistant.components.influxdb
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1037, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/usr/src/homeassistant/homeassistant/components/influxdb/__init__.py", line 15, in <module>
    from influxdb import InfluxDBClient, exceptions
  File "/usr/local/lib/python3.12/site-packages/influxdb/__init__.py", line 10, in <module>
    from .dataframe_client import DataFrameClient
  File "/usr/local/lib/python3.12/site-packages/influxdb/dataframe_client.py", line 12, in <module>
    import pandas
  File "/usr/local/lib/python3.12/site-packages/pandas/__init__.py", line 46, in <module>
    from pandas.core.api import (
  File "/usr/local/lib/python3.12/site-packages/pandas/core/api.py", line 47, in <module>
    from pandas.core.groupby import (
  File "/usr/local/lib/python3.12/site-packages/pandas/core/groupby/__init__.py", line 1, in <module>
    from pandas.core.groupby.generic import (
  File "/usr/local/lib/python3.12/site-packages/pandas/core/groupby/generic.py", line 67, in <module>
    from pandas.core.frame import DataFrame
  File "/usr/local/lib/python3.12/site-packages/pandas/core/frame.py", line 142, in <module>
    from pandas.core.generic import (
  File "/usr/local/lib/python3.12/site-packages/pandas/core/generic.py", line 187, in <module>
    from pandas.core.window import (
  File "/usr/local/lib/python3.12/site-packages/pandas/core/window/__init__.py", line 1, in <module>
    from pandas.core.window.ewm import (
  File "/usr/local/lib/python3.12/site-packages/pandas/core/window/ewm.py", line 49, in <module>
    from pandas.core.window.rolling import (
SyntaxError: source code string cannot contain null bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 979, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1048, in _get_component
    raise ImportError(f"Exception importing {self.pkg_path}") from err
ImportError: Exception importing homeassistant.components.influxdb

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1037, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/usr/src/homeassistant/homeassistant/components/influxdb/__init__.py", line 15, in <module>
    from influxdb import InfluxDBClient, exceptions
  File "/usr/local/lib/python3.12/site-packages/influxdb/__init__.py", line 10, in <module>
    from .dataframe_client import DataFrameClient
  File "/usr/local/lib/python3.12/site-packages/influxdb/dataframe_client.py", line 12, in <module>
    import pandas
  File "/usr/local/lib/python3.12/site-packages/pandas/__init__.py", line 46, in <module>
    from pandas.core.api import (
  File "/usr/local/lib/python3.12/site-packages/pandas/core/api.py", line 47, in <module>
    from pandas.core.groupby import (
  File "/usr/local/lib/python3.12/site-packages/pandas/core/groupby/__init__.py", line 1, in <module>
    from pandas.core.groupby.generic import (
  File "/usr/local/lib/python3.12/site-packages/pandas/core/groupby/generic.py", line 67, in <module>
    from pandas.core.frame import DataFrame
  File "/usr/local/lib/python3.12/site-packages/pandas/core/frame.py", line 142, in <module>
    from pandas.core.generic import (
  File "/usr/local/lib/python3.12/site-packages/pandas/core/generic.py", line 187, in <module>
    from pandas.core.window import (
  File "/usr/local/lib/python3.12/site-packages/pandas/core/window/__init__.py", line 1, in <module>
    from pandas.core.window.ewm import (
  File "/usr/local/lib/python3.12/site-packages/pandas/core/window/ewm.py", line 49, in <module>
    from pandas.core.window.rolling import (
SyntaxError: source code string cannot contain null bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 316, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 997, in async_get_component
    self._component_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 989, in async_get_component
    comp = self._get_component()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1048, in _get_component
    raise ImportError(f"Exception importing {self.pkg_path}") from err
ImportError: Exception importing homeassistant.components.influxdb

The add-on protocol itself shows no failures and influxes seem to be running. A restart of the add-on or HA did not make a difference.

Any advice what went wrong or how I can get rid of this error without any data loss?

Thanks in advance.

Running HA on ThinkCentre M910q i5-6500T with 256 GB Nvme 16GM Memory  as Ubuntu Server + VirtualBox

**Comment by Palmdale95** [comment]
After a reboot of the system the add-on tells it is starting but nothing happens:

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service base-addon-banner: starting
-----------------------------------------------------------

 Add-on: InfluxDB
 Scalable datastore for metrics, events, and real-time analytics
-----------------------------------------------------------
 Add-on version: 5.0.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 12.1  (amd64 / qemux86-64)
 Home Assistant Core: 2024.4.1
 Home Assistant Supervisor: 2024.03.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-timezone: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
[15:41:14] INFO: Configuring timezone (Europe/Berlin)...
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service base-addon-timezone successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/create-users.sh
cont-init: info: /etc/cont-init.d/create-users.sh exited 0
cont-init: info: running /etc/cont-init.d/influxdb.sh
cont-init: info: /etc/cont-init.d/influxdb.sh exited 0
cont-init: info: running /etc/cont-init.d/kapacitor.sh
cont-init: info: /etc/cont-init.d/kapacitor.sh exited 0
cont-init: info: running /etc/cont-init.d/nginx.sh
cont-init: info: /etc/cont-init.d/nginx.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun chronograf (no readiness notification)
services-up: info: copying legacy longrun influxdb (no readiness notification)
services-up: info: copying legacy longrun kapacitor (no readiness notification)
services-up: info: copying legacy longrun nginx (no readiness notification)
[15:41:16] INFO: Kapacitor is waiting until InfluxDB is available...
[15:41:16] INFO: Chronograf is waiting until InfluxDB is available...
s6-rc: info: service legacy-services successfully started
[15:41:16] INFO: Starting the InfluxDB...

**Comment by Palmdale95** [comment]
While trying to fix gut this message now:
[14:15:20] INFO: Starting the InfluxDB...
ts=2024-04-07T12:15:28.843861Z lvl=error msg="Cannot read corrupt tsm file, renaming" log_id=0oQ7aidl000 engine=tsm1 service=filestore path=/data/influxdb/data/home_assistant/autogen/222/000000012-000000002.tsm id=0 error="mmapAccessor: invalid indexStart"

**Comment by Palmdale95** [comment]
Node_red_companion integration was the issue. After an update most of the data could be recovered.
