### ISSUE TITLE
Supervisor died

### ISSUE THREAD

**Issue by Mace404** [hassio-addons/addon-influxdb#68]
# Problem/Motivation
InfluxDB does not start or crashes shortly after start

## Expected behavior
InfluxDB starts

## Actual behavior
InfluxDB starts and crashes during startup or shortly after

## Steps to reproduce
Start InfluxDB

## Proposed changes
n/a

I'm running the latest version of the addon and since yesterday the addon was stopped and when I start it, it directly stops or it stops after a short period.

I'm running Home Assistant OS 3.11 with Home Assistant Core 0.106.1 in a VM (Unraid)
Supervisor version is 206.

This is what I get in the log:

```
created by github.com/influxdata/influxdb/services/subscriber.(*Service).updateSubs
	/go/src/github.com/influxdata/influxdb/services/subscriber/service.go:312 +0xe77
goroutine 364 [chan receive]:
github.com/influxdata/influxdb/services/subscriber.chanWriter.Run(0xc00555ba40, 0x2123fc0, 0xc000738a00, 0xc00029b988, 0xc00029b990, 0xc0008117a0)
	/go/src/github.com/influxdata/influxdb/services/subscriber/service.go:372 +0x4e
github.com/influxdata/influxdb/services/subscriber.(*Service).updateSubs.func1(0xc0037183a0, 0xc00555ba40, 0x2123fc0, 0xc000738a00, 0xc00029b988, 0xc00029b990, 0xc0008117a0)
	/go/src/github.com/influxdata/influxdb/services/subscriber/service.go:314 +0x65
created by github.com/influxdata/influxdb/services/subscriber.(*Service).updateSubs
	/go/src/github.com/influxdata/influxdb/services/subscriber/service.go:312 +0xe77
goroutine 365 [chan receive]:
github.com/influxdata/influxdb/services/subscriber.chanWriter.Run(0xc00555ba40, 0x2123fc0, 0xc000738a00, 0xc00029b988, 0xc00029b990, 0xc0008117a0)
	/go/src/github.com/influxdata/influxdb/services/subscriber/service.go:372 +0x4e
github.com/influxdata/influxdb/services/subscriber.(*Service).updateSubs.func1(0xc0037183a0, 0xc00555ba40, 0x2123fc0, 0xc000738a00, 0xc00029b988, 0xc00029b990, 0xc0008117a0)
	/go/src/github.com/influxdata/influxdb/services/subscriber/service.go:314 +0x65
created by github.com/influxdata/influxdb/services/subscriber.(*Service).updateSubs
	/go/src/github.com/influxdata/influxdb/services/subscriber/service.go:312 +0xe77
goroutine 366 [chan receive]:
github.com/influxdata/influxdb/services/subscriber.chanWriter.Run(0xc00555ba40, 0x2123fc0, 0xc000738a00, 0xc00029b988, 0xc00029b990, 0xc0008117a0)
	/go/src/github.com/influxdata/influxdb/services/subscriber/service.go:372 +0x4e
github.com/influxdata/influxdb/services/subscriber.(*Service).updateSubs.func1(0xc0037183a0, 0xc00555ba40, 0x2123fc0, 0xc000738a00, 0xc00029b988, 0xc00029b990, 0xc0008117a0)
	/go/src/github.com/influxdata/influxdb/services/subscriber/service.go:314 +0x65
created by github.com/influxdata/influxdb/services/subscriber.(*Service).updateSubs
	/go/src/github.com/influxdata/influxdb/services/subscriber/service.go:312 +0xe77
goroutine 367 [chan receive]:
github.com/influxdata/influxdb/services/subscriber.chanWriter.Run(0xc00555ba40, 0x2123fc0, 0xc000738a00, 0xc00029b988, 0xc00029b990, 0xc0008117a0)
	/go/src/github.com/influxdata/influxdb/services/subscriber/service.go:372 +0x4e
github.com/influxdata/influxdb/services/subscriber.(*Service).updateSubs.func1(0xc0037183a0, 0xc00555ba40, 0x2123fc0, 0xc000738a00, 0xc00029b988, 0xc00029b990, 0xc0008117a0)
	/go/src/github.com/influxdata/influxdb/services/subscriber/service.go:314 +0x65
created by github.com/influxdata/influxdb/services/subscriber.(*Service).updateSubs
	/go/src/github.com/influxdata/influxdb/services/subscriber/service.go:312 +0xe77
goroutine 368 [chan receive]:
github.com/influxdata/influxdb/services/subscriber.chanWriter.Run(0xc00555ba40, 0x2123fc0, 0xc000738a00, 0xc00029b988, 0xc00029b990, 0xc0008117a0)
	/go/src/github.com/influxdata/influxdb/services/subscriber/service.go:372 +0x4e
github.com/influxdata/influxdb/services/subscriber.(*Service).updateSubs.func1(0xc0037183a0, 0xc00555ba40, 0x2123fc0, 0xc000738a00, 0xc00029b988, 0xc00029b990, 0xc0008117a0)
	/go/src/github.com/influxdata/influxdb/services/subscriber/service.go:314 +0x65
created by github.com/influxdata/influxdb/services/subscriber.(*Service).updateSubs
	/go/src/github.com/influxdata/influxdb/services/subscriber/service.go:312 +0xe77
goroutine 369 [chan receive]:
github.com/influxdata/influxdb/services/subscriber.chanWriter.Run(0xc00555ba40, 0x2123fc0, 0xc000738a00, 0xc00029b988, 0xc00029b990, 0xc0008117a0)
	/go/src/github.com/influxdata/influxdb/services/subscriber/service.go:372 +0x4e
github.com/influxdata/influxdb/services/subscriber.(*Service).updateSubs.func1(0xc0037183a0, 0xc00555ba40, 0x2123fc0, 0xc000738a00, 0xc00029b988, 0xc00029b990, 0xc0008117a0)
	/go/src/github.com/influxdata/influxdb/services/subscriber/service.go:314 +0x65
created by github.com/influxdata/influxdb/services/subscriber.(*Service).updateSubs
	/go/src/github.com/influxdata/influxdb/services/subscriber/service.go:312 +0xe77
goroutine 386 [chan receive]:
github.com/influxdata/influxdb/services/subscriber.chanWriter.Run(0xc00555ba40, 0x2123fc0, 0xc000738a00, 0xc00029b988, 0xc00029b990, 0xc0008117a0)
	/go/src/github.com/influxdata/influxdb/services/subscriber/service.go:372 +0x4e
github.com/influxdata/influxdb/services/subscriber.(*Service).updateSubs.func1(0xc0037183a0, 0xc00555ba40, 0x2123fc0, 0xc000738a00, 0xc00029b988, 0xc00029b990, 0xc0008117a0)
	/go/src/github.com/influxdata/influxdb/services/subscriber/service.go:314 +0x65
created by github.com/influxdata/influxdb/services/subscriber.(*Service).updateSubs
	/go/src/github.com/influxdata/influxdb/services/subscriber/service.go:312 +0xe77
goroutine 387 [chan receive]:
github.com/influxdata/influxdb/services/subscriber.chanWriter.Run(0xc00555ba40, 0x2123fc0, 0xc000738a00, 0xc00029b988, 0xc00029b990, 0xc0008117a0)
	/go/src/github.com/influxdata/influxdb/services/subscriber/service.go:372 +0x4e
github.com/influxdata/influxdb/services/subscriber.(*Service).updateSubs.func1(0xc0037183a0, 0xc00555ba40, 0x2123fc0, 0xc000738a00, 0xc00029b988, 0xc00029b990, 0xc0008117a0)
	/go/src/github.com/influxdata/influxdb/services/subscriber/service.go:314 +0x65
created by github.com/influxdata/influxdb/services/subscriber.(*Service).updateSubs
	/go/src/github.com/influxdata/influxdb/services/subscriber/service.go:312 +0xe77
goroutine 388 [chan receive]:
github.com/influxdata/influxdb/services/subscriber.chanWriter.Run(0xc00555ba40, 0x2123fc0, 0xc000738a00, 0xc00029b988, 0xc00029b990, 0xc0008117a0)
	/go/src/github.com/influxdata/influxdb/services/subscriber/service.go:372 +0x4e
github.com/influxdata/influxdb/services/subscriber.(*Service).updateSubs.func1(0xc0037183a0, 0xc00555ba40, 0x2123fc0, 0xc000738a00, 0xc00029b988, 0xc00029b990, 0xc0008117a0)
	/go/src/github.com/influxdata/influxdb/services/subscriber/service.go:314 +0x65
created by github.com/influxdata/influxdb/services/subscriber.(*Service).updateSubs
	/go/src/github.com/influxdata/influxdb/services/subscriber/service.go:312 +0xe77
goroutine 389 [chan receive]:
github.com/influxdata/influxdb/services/subscriber.chanWriter.Run(0xc00555ba40, 0x2123fc0, 0xc000738a00, 0xc00029b988, 0xc00029b990, 0xc0008117a0)
	/go/src/github.com/influxdata/influxdb/services/subscriber/service.go:372 +0x4e
github.com/influxdata/influxdb/services/subscriber.(*Service).updateSubs.func1(0xc0037183a0, 0xc00555ba40, 0x2123fc0, 0xc000738a00, 0xc00029b988, 0xc00029b990, 0xc0008117a0)
	/go/src/github.com/influxdata/influxdb/services/subscriber/service.go:314 +0x65
created by github.com/influxdata/influxdb/services/subscriber.(*Service).updateSubs
	/go/src/github.com/influxdata/influxdb/services/subscriber/service.go:312 +0xe77
goroutine 390 [chan receive]:
github.com/influxdata/influxdb/services/subscriber.chanWriter.Run(0xc00555ba40, 0x2123fc0, 0xc000738a00, 0xc00029b988, 0xc00029b990, 0xc0008117a0)
	/go/src/github.com/influxdata/influxdb/services/subscriber/service.go:372 +0x4e
github.com/influxdata/influxdb/services/subscriber.(*Service).updateSubs.func1(0xc0037183a0, 0xc00555ba40, 0x2123fc0, 0xc000738a00, 0xc00029b988, 0xc00029b990, 0xc0008117a0)
	/go/src/github.com/influxdata/influxdb/services/subscriber/service.go:314 +0x65
created by github.com/influxdata/influxdb/services/subscriber.(*Service).updateSubs
	/go/src/github.com/influxdata/influxdb/services/subscriber/service.go:312 +0xe77
goroutine 391 [chan receive]:
github.com/influxdata/influxdb/services/subscriber.chanWriter.Run(0xc00555ba40, 0x2123fc0, 0xc000738a00, 0xc00029b988, 0xc00029b990, 0xc0008117a0)
	/go/src/github.com/influxdata/influxdb/services/subscriber/service.go:372 +0x4e
github.com/influxdata/influxdb/services/subscriber.(*Service).updateSubs.func1(0xc0037183a0, 0xc00555ba40, 0x2123fc0, 0xc000738a00, 0xc00029b988, 0xc00029b990, 0xc0008117a0)
	/go/src/github.com/influxdata/influxdb/services/subscriber/service.go:314 +0x65
created by github.com/influxdata/influxdb/services/subscriber.(*Service).updateSubs
	/go/src/github.com/influxdata/influxdb/services/subscriber/service.go:312 +0xe77
s6-svwait: fatal: supervisor died
[s6-finish] sending all processes the TERM signal.
```

**Comment by przemo** [comment]
Same issue. InfluxDB addon starts in pain, consuming 100% CPU for several minutes, it crashes/shuts off regularly.

**Comment by frenck** [comment]
The only thing I can think of is running out of memory.
